ALTER TABLE t_p71061117_crm_client_managemen.candidates
  ADD COLUMN IF NOT EXISTS birth_date TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS citizenship TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS has_inn BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_snils BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS relations TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS arrival_date TEXT NOT NULL DEFAULT '';